language: php
php:
- 5.3
- hhvm
- nightly

before_script:
- sudo apt-get install ncftp

script:
#- ./notest.sh
#after_success:
- "ncftpput -R -u $USER -p $PASWD ks3309521.kimsufi.com /web/wp-content/themes ./polskiecegielnie"
