language: php
php:
- 5.3
- hhvm
- nightly

script:
- ./notest.sh

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: 
    - "polskiecegielnie"
  skip_cleanup: true
  on:
    tags: true
