language: php
php:
- 5.3
- hhvm
- nightly

before_script:
- sudo apt-get install ncftp

script:
- "ncftpput -R -u $USER -p $PASWD ks3309521.kimsufi.com /web/wp-content/themes ./polskiecegielnie"

notifications:
  email:
    - dawidpych+5450a7b7c1b20b981571eb16+55d6f9b7c7183f8c62f628c6+d6a1f44f7bbd18dc2f83d8278d639ff987b83243@boards.trello.com
    - dawidpych@gmail.com
  on_success: [always]
  on_failure: [always]
#  template:
#    "%{repository} (%{commit}) : %{meddage} \n Build details: %{build_url}"
